service: sls-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'
        - Effect: Allow
          Action:
           - secretsmanager:*
          Resource: '*'
  
layers:
  dependencies:
    path: third_party/
    name: ${self:service}-${sls:stage}-layer
    compatibleRuntimes:
      - python3.10

functions:
  create_inventory:
    handler: create.handler
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /
          method: post

  list_inventory:
    handler: list.handler
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /
          method: get